import type { Country, HistoricalEvent, MemoryRecord, MemoryType, NationalMemory, WarState } from '../../types/game'

export function memoryKey(owner: string, target: string) { return `${owner}:${target}` }
export function createMemoryState(countries: Country[]) { const records: Record<string, NationalMemory> = {}; countries.forEach((owner) => countries.forEach((target) => { if (owner.id !== target.id) records[memoryKey(owner.id, target.id)] = { id: memoryKey(owner.id, target.id), ownerCountryId: owner.id, targetCountryId: target.id, memories: [], sentiment: 0, trust: 50, fear: 0, respect: 20, grudge: 0, threat: 0 } })); return records }
export function recordHistoricalEvent(events: HistoricalEvent[], date: string, type: HistoricalEvent['type'], title: string, description: string, countries: string[], importance: number, regions: string[] = [], causeEventId?: string) { const event: HistoricalEvent = { id: `history-${Date.now()}-${events.length}`, date, type, title, description, countries, importance, regions, tags: [type], causeEventId }; return { event, events: importance >= 40 ? [event, ...events].slice(0, 120) : events } }
export function addNationalMemory(records: Record<string, NationalMemory>, owner: string, target: string, type: MemoryType, description: string, strength: number, sourceEventId?: string) { const key = memoryKey(owner, target); const current = records[key] ?? { id: key, ownerCountryId: owner, targetCountryId: target, memories: [], sentiment: 0, trust: 50, fear: 0, respect: 20, grudge: 0, threat: 0 }; const similar = current.memories.find((memory) => memory.type === type); const memories = similar ? current.memories.map((memory) => memory === similar ? { ...memory, strength: Math.min(100, memory.strength + strength), date: description } : memory) : [{ id: `memory-${Date.now()}`, date: '', type, strength: Math.min(100, strength), description, sourceEventId, decayRate: type === '침공' || type === '배신' || type === '협정 위반' ? 0.05 : 0.12 }, ...current.memories].slice(0, 20); const next = { ...current, memories, sentiment: Math.max(-100, Math.min(100, current.sentiment + (type === '무역' || type === '원조' || type === '동맹' ? 3 : type === '침공' || type === '배신' || type === '전쟁' ? -8 : 0))), trust: Math.max(0, Math.min(100, current.trust + (type === '동맹' || type === '원조' ? 4 : type === '배신' || type === '협정 위반' ? -18 : 0))), respect: Math.max(0, Math.min(100, current.respect + (type === '전쟁' ? 2 : 0))), grudge: Math.max(0, Math.min(100, current.grudge + (type === '침공' || type === '영토 점령' || type === '배신' ? strength * 0.35 : type === '평화' ? -2 : 0))) }; return { ...records, [key]: next }
}
export function recordPair(records: Record<string, NationalMemory>, a: string, b: string, type: MemoryType, description: string, strength: number, eventId?: string) { let next = addNationalMemory(records, a, b, type, description, strength, eventId); return type === '원조' || type === '무역' || type === '동맹' || type === '평화' ? addNationalMemory(next, b, a, type, description, strength, eventId) : next }
export function decayMemories(records: Record<string, NationalMemory>) { return Object.fromEntries(Object.entries(records).map(([key, record]) => [key, { ...record, memories: record.memories.map((memory) => ({ ...memory, strength: Math.max(0, memory.strength - memory.decayRate) })).filter((memory) => memory.strength > 1), grudge: Math.max(0, record.grudge - 0.08), fear: Math.max(0, record.fear - 0.1), threat: Math.max(0, record.threat - 0.1) }])) }
export function calculateThreat(observer: Country, target: Country, memory?: NationalMemory) { const military = Math.min(60, target.military / Math.max(1, observer.military) * 35); const memoryThreat = (memory?.grudge ?? 0) * 0.35 + (memory?.fear ?? 0) * 0.25; return Math.max(0, Math.min(100, military + memoryThreat)) }
export function updateThreats(records: Record<string, NationalMemory>, countries: Country[]) { const next = { ...records }; countries.forEach((observer) => countries.forEach((target) => { if (observer.id === target.id) return; const key = memoryKey(observer.id, target.id); const memory = next[key]; if (memory) next[key] = { ...memory, threat: calculateThreat(observer, target, memory) } })); return next }
export function warMemory(records: Record<string, NationalMemory>, war: WarState, winner?: string) { const loser = winner === war.attacker ? war.defender : war.attacker; let next = recordPair(records, war.attacker, war.defender, '전쟁', `${war.attacker}와 ${war.defender} 사이의 전쟁`, 35); if (winner) { next = recordPair(next, winner, loser, '평화', '전쟁이 평화협정으로 종결되었습니다.', 20); const winnerRecord = next[memoryKey(loser, winner)]; if (winnerRecord) next[memoryKey(loser, winner)] = { ...winnerRecord, fear: Math.min(100, winnerRecord.fear + 12), grudge: Math.min(100, winnerRecord.grudge + 8) } } return next }
