import type { AirForce, AircraftStock, Country, RegionState } from '../../types/game'

export const emptyAircraft = (): AircraftStock => ({ fighters: 0, cas: 0, bombers: 0, maritimePatrol: 0, transports: 0 })
export function createInitialAirForces(countries: Country[], territories: Record<string, RegionState[]>): AirForce[] { return countries.map((country) => ({ id: `air-${country.id}-1`, countryId: country.id, name: `${country.name} 제1항공군`, aircraft: { fighters: 80, cas: 35, bombers: 15, maritimePatrol: 8, transports: 12 }, baseRegionId: territories[country.id]?.[0]?.id ?? '', operationRegionIds: [], mission: '대기', readiness: 82, training: 55, experience: 10, fuel: 80 })) }
export function airPower(air: AirForce) { return (air.aircraft.fighters * 1.2 + air.aircraft.cas * 0.7 + air.aircraft.bombers * 0.5 + air.aircraft.maritimePatrol * 0.4) * (0.55 + air.training / 200) * (air.readiness / 100) * (air.fuel / 100) }
export function updateAirForces(airForces: AirForce[], regions: RegionState[], wars: { attacker: string; defender: string; active: boolean }[]) {
  const activeCountries = new Set(wars.filter((war) => war.active).flatMap((war) => [war.attacker, war.defender])); const next = airForces.map((air) => ({ ...air, mission: activeCountries.has(air.countryId) && air.mission === '대기' ? '제공권 확보' as const : air.mission, readiness: Math.min(100, air.readiness + (air.mission === '대기' ? 3 : -2)), fuel: Math.max(10, air.fuel - (air.mission === '대기' ? 1 : 4)), operationRegionIds: air.operationRegionIds.length ? air.operationRegionIds : regions.filter((region) => region.ownerCountryId === air.countryId).slice(0, 3).map((region) => region.id) })); const superiority: Record<string, Record<string, number>> = {}
  for (const region of regions) { const participants = next.filter((air) => air.operationRegionIds.includes(region.id) || air.baseRegionId === region.id); const byCountry = new Map<string, number>(); participants.forEach((air) => byCountry.set(air.countryId, (byCountry.get(air.countryId) ?? 0) + airPower(air))); const total = [...byCountry.values()].reduce((a, b) => a + b, 0) || 1; superiority[region.id] = Object.fromEntries([...byCountry.entries()].map(([id, power]) => [id, Math.round(power / total * 100)])); }
  return { airForces: next, airSuperiority: superiority, activeCountries }
}
