import type { ResearchCategory } from '../../types/game'

export interface TechnologyDefinition { id: string; name: string; category: ResearchCategory; description: string; researchMonths: number; prerequisites: string[]; effects: string[]; aiWeight: number }

export const technologies: TechnologyDefinition[] = [
  { id: 'industrialization_1', name: '산업화 I', category: '산업', description: '산업 기반을 확립합니다.', researchMonths: 4, prerequisites: [], effects: ['산업력 +5%'], aiWeight: 9 }, { id: 'industrialization_2', name: '산업화 II', category: '산업', description: '생산 체계를 고도화합니다.', researchMonths: 6, prerequisites: ['industrialization_1'], effects: ['산업력 +8%'], aiWeight: 10 }, { id: 'mass_production', name: '대량 생산', category: '산업', description: '대규모 생산 체계를 구축합니다.', researchMonths: 8, prerequisites: ['industrialization_2'], effects: ['산업 생산 +10%', '군수 생산 +5%'], aiWeight: 10 }, { id: 'automation', name: '자동화', category: '산업', description: '자동화된 생산을 도입합니다.', researchMonths: 10, prerequisites: ['mass_production'], effects: ['산업력 +10%', '실업률 소폭 증가'], aiWeight: 8 }, { id: 'advanced_manufacturing', name: '첨단 제조', category: '산업', description: '고부가가치 제조 역량을 확보합니다.', researchMonths: 12, prerequisites: ['automation'], effects: ['산업력 +15%', '연구력 +5%'], aiWeight: 9 },
  { id: 'economics', name: '경제학', category: '경제', description: '경제 운용의 기초를 연구합니다.', researchMonths: 4, prerequisites: [], effects: ['GDP 성장률 +0.2%'], aiWeight: 9 }, { id: 'financial_system', name: '금융 시스템', category: '경제', description: '국가 금융 체계를 정비합니다.', researchMonths: 6, prerequisites: ['economics'], effects: ['국고 수입 +5%'], aiWeight: 8 }, { id: 'modern_finance', name: '현대 금융', category: '경제', description: '현대적인 금융 도구를 사용합니다.', researchMonths: 8, prerequisites: ['financial_system'], effects: ['GDP 성장률 +0.3%', '국고 수입 +5%'], aiWeight: 9 }, { id: 'global_trade', name: '글로벌 무역', category: '경제', description: '국제 무역을 확대합니다.', researchMonths: 8, prerequisites: ['financial_system'], effects: ['무역 수입 증가', '외교 관계 보너스'], aiWeight: 8 }, { id: 'economic_digitization', name: '경제 디지털화', category: '경제', description: '데이터 기반 경제를 구축합니다.', researchMonths: 10, prerequisites: ['modern_finance'], effects: ['GDP 성장률 증가', '연구력 증가'], aiWeight: 10 },
  { id: 'modern_military', name: '현대 군사학', category: '군사', description: '현대전의 기본 원리를 정립합니다.', researchMonths: 5, prerequisites: [], effects: ['군사력 +5%'], aiWeight: 10 }, { id: 'mechanized_forces', name: '기계화 부대', category: '군사', description: '기동력 있는 지상군을 편성합니다.', researchMonths: 7, prerequisites: ['modern_military'], effects: ['지상군 전투력 +10%'], aiWeight: 10 }, { id: 'modern_artillery', name: '현대 포병', category: '군사', description: '포병 화력을 현대화합니다.', researchMonths: 6, prerequisites: ['modern_military'], effects: ['지상군 공격력 +8%'], aiWeight: 8 }, { id: 'air_force_modernization', name: '공군 현대화', category: '군사', description: '공군 전력을 현대화합니다.', researchMonths: 7, prerequisites: ['modern_military'], effects: ['공군 전투력 +10%'], aiWeight: 9 }, { id: 'naval_modernization', name: '해군 현대화', category: '군사', description: '해상 전력을 현대화합니다.', researchMonths: 7, prerequisites: ['modern_military'], effects: ['해군 전투력 +10%'], aiWeight: 8 }, { id: 'combined_arms', name: '통합전', category: '군사', description: '육·해·공 합동 작전을 수행합니다.', researchMonths: 10, prerequisites: ['mechanized_forces', 'air_force_modernization'], effects: ['전투력 +15%'], aiWeight: 10 }, { id: 'precision_strike', name: '정밀 타격', category: '군사', description: '정밀 유도 공격을 운용합니다.', researchMonths: 12, prerequisites: ['air_force_modernization', 'combined_arms'], effects: ['공격력 +15%'], aiWeight: 9 }, { id: 'military_ai', name: '군사 AI', category: '군사', description: '전장 의사결정을 자동화합니다.', researchMonths: 18, prerequisites: ['precision_strike', 'economic_digitization'], effects: ['전투력 +15%', '군사 유지비 감소'], aiWeight: 10 },
  { id: 'basic_science', name: '기초 과학', category: '과학', description: '과학 연구의 기반을 마련합니다.', researchMonths: 4, prerequisites: [], effects: ['연구력 +5%'], aiWeight: 10 }, { id: 'higher_education', name: '고등 교육', category: '과학', description: '고급 인재를 양성합니다.', researchMonths: 7, prerequisites: ['basic_science'], effects: ['연구 속도 +10%', '연구 슬롯 +1'], aiWeight: 10 }, { id: 'electronics', name: '전자공학', category: '과학', description: '전자 기술을 산업에 적용합니다.', researchMonths: 7, prerequisites: ['basic_science'], effects: ['연구 속도 +5%', '산업력 +3%'], aiWeight: 9 }, { id: 'computers', name: '컴퓨터', category: '과학', description: '계산 자동화 기술을 확보합니다.', researchMonths: 9, prerequisites: ['electronics'], effects: ['연구력 +10%'], aiWeight: 9 }, { id: 'internet', name: '인터넷', category: '과학', description: '정보 연결망을 구축합니다.', researchMonths: 12, prerequisites: ['computers'], effects: ['GDP 성장률 +0.3%', '연구 속도 +10%'], aiWeight: 10 }, { id: 'artificial_intelligence', name: '인공지능', category: '과학', description: '지능형 자동화 시대를 엽니다.', researchMonths: 18, prerequisites: ['internet', 'computers'], effects: ['연구 속도 +20%', '산업력 +10%', '군사력 +5%'], aiWeight: 10 },
  { id: 'welfare_administration', name: '복지 행정', category: '사회', description: '효율적인 복지 전달 체계를 만듭니다.', researchMonths: 5, prerequisites: [], effects: ['안정도 +3'], aiWeight: 7 }, { id: 'public_health', name: '공공 의료', category: '사회', description: '국민 건강을 개선합니다.', researchMonths: 7, prerequisites: ['welfare_administration'], effects: ['인구 성장 증가', '안정도 +3'], aiWeight: 8 }, { id: 'modern_education', name: '현대 교육', category: '사회', description: '교육을 국가 발전의 기반으로 삼습니다.', researchMonths: 8, prerequisites: ['higher_education'], effects: ['연구 속도 +10%', '연구력 증가'], aiWeight: 9 }, { id: 'social_digitalization', name: '사회 디지털화', category: '사회', description: '행정과 사회 서비스를 디지털화합니다.', researchMonths: 10, prerequisites: ['internet'], effects: ['행정 효율 증가', 'GDP 성장률 증가'], aiWeight: 8 },
  { id: 'diplomacy', name: '외교학', category: '외교', description: '국가 간 관계를 관리하는 기술입니다.', researchMonths: 5, prerequisites: [], effects: ['관계 개선 속도 증가'], aiWeight: 7 }, { id: 'international_cooperation', name: '국제 협력', category: '외교', description: '동맹과 무역의 기반을 강화합니다.', researchMonths: 8, prerequisites: ['diplomacy'], effects: ['동맹·무역 보너스'], aiWeight: 8 }, { id: 'global_diplomacy', name: '글로벌 외교', category: '외교', description: '국제적 영향력을 확대합니다.', researchMonths: 10, prerequisites: ['international_cooperation'], effects: ['외교 협정 비용 감소'], aiWeight: 8 }, { id: 'international_organization', name: '국제기구', category: '외교', description: '국제 질서를 주도합니다.', researchMonths: 14, prerequisites: ['global_diplomacy'], effects: ['국제 협정 보너스'], aiWeight: 7 },
]
