import type { BuildingId, Country, RegionState, ResourceProduction } from '../../types/game'
import { buildings } from '../buildings/buildingData'
import { emptyResources } from '../resources/resourceUtils'

export const normalizeRegion = (region: RegionState): RegionState => ({ ...region, ownerCountryId: region.ownerCountryId ?? region.originalOwner, population: region.population ?? 10, development: region.development ?? 40, infrastructure: region.infrastructure ?? 40, industrialCapacity: region.industrialCapacity ?? 5, civilianFactories: region.civilianFactories ?? 0, militaryFactories: region.militaryFactories ?? 0, researchFacilities: region.researchFacilities ?? 0, resourceProduction: region.resourceProduction ?? emptyResources(), buildings: region.buildings ?? [], isBorderRegion: region.isBorderRegion ?? false, infrastructureDamage: region.infrastructureDamage ?? 0 })

export const regionSlots = (region: RegionState) => Math.max(2, Math.floor(normalizeRegion(region).development / 8))
export const regionOutput = (rawRegion: RegionState): ResourceProduction => { const region = normalizeRegion(rawRegion); const result = { ...region.resourceProduction }; const mines = region.buildings.filter((building) => building.id === 'mine').reduce((sum, building) => sum + building.level, 0); Object.keys(result).forEach((key) => { const typedKey = key as keyof ResourceProduction; result[typedKey] *= 1 + mines * 0.2 }); return result }
export const totalResources = (regions: RegionState[]) => regions.reduce((total, region) => { const output = regionOutput(region); Object.keys(total).forEach((key) => { const typedKey = key as keyof ResourceProduction; total[typedKey] += output[typedKey] }); return total }, emptyResources())
export function canBuild(rawRegion: RegionState, buildingId: BuildingId) { const region = normalizeRegion(rawRegion); const definition = buildings.find((building) => building.id === buildingId)!; if (region.buildings.length >= regionSlots(region)) return '건물 슬롯이 부족합니다.'; if (buildingId === 'port' && region.infrastructure < 30) return '항만은 인프라 30 이상인 지역에 건설할 수 있습니다.'; if (buildingId === 'mine' && Object.values(region.resourceProduction).every((value) => value <= 0)) return '자원이 있는 지역에만 광산을 건설할 수 있습니다.'; if (buildingId === 'university' && region.development < 35) return '대학은 개발도 35 이상인 지역에 건설할 수 있습니다.'; return definition ? undefined : '건물을 찾을 수 없습니다.' }
export function advanceConstruction(country: Country, rawRegions: RegionState[]) { const regions = rawRegions.map(normalizeRegion); const completed: string[] = []; const queue = (country.constructionQueue ?? []).map((project) => ({ ...project, monthsRemaining: project.monthsRemaining - 1 })).filter((project) => { if (project.monthsRemaining > 0) return true; const region = regions.find((item) => item.id === project.regionId); if (region) { const existing = region.buildings.find((building) => building.id === project.buildingId); if (existing) existing.level += 1; else region.buildings.push({ id: project.buildingId, level: 1 }); if (project.buildingId === 'railway') region.infrastructure = Math.min(100, region.infrastructure + 8); completed.push(`${region.name}의 ${buildings.find((building) => building.id === project.buildingId)?.name ?? '건물'} 건설이 완료되었습니다.`) } return false }); return { country: { ...country, constructionQueue: queue }, regions, completed } }
