import type { Country, NationalFocusState, PoliticalState } from '../../types/game'
export interface NationalFocus { id: string; name: string; description: string; months: number; prerequisites: string[]; effects: { stability?: number; approval?: number; industry?: number; gdpGrowth?: number; military?: number } }
export const nationalFocuses: NationalFocus[] = [
  { id: 'industrial_modernization', name: '산업 현대화', description: '국가 산업 기반을 확장합니다.', months: 6, prerequisites: [], effects: { industry: 3, gdpGrowth: 0.4 } },
  { id: 'military_expansion', name: '군비 확장', description: '군수 산업과 국방 역량을 강화합니다.', months: 6, prerequisites: [], effects: { military: 3, stability: -1 } },
  { id: 'welfare_state', name: '복지 국가', description: '국민 생활과 사회 안정을 개선합니다.', months: 6, prerequisites: [], effects: { approval: 4, stability: 3 } },
  { id: 'diplomatic_reform', name: '외교 개혁', description: '국제 협력과 외교 역량을 강화합니다.', months: 5, prerequisites: [], effects: { approval: 2, stability: 1 } },
]
export function startFocus(current: NationalFocusState, id: string, political: PoliticalState) { if (current.activeId || current.completed.includes(id)) return { current, error: '이미 진행 중이거나 완료한 국가 중점입니다.' }; const power = political.politicalPower ?? 60; if (power < 15) return { current, error: '국가 중점을 시작하려면 정치력 15가 필요합니다.' }; return { current: { ...current, activeId: id, progress: 0 }, political: { ...political, politicalPower: power - 15 } } }
export function advanceFocus(country: Country, political: PoliticalState, current: NationalFocusState): { country: Country; political: PoliticalState; focus: NationalFocusState; completed?: NationalFocus } { if (!current.activeId) return { country, political, focus: current }; const focus = nationalFocuses.find((item) => item.id === current.activeId); if (!focus) return { country, political, focus: { ...current, activeId: null } }; const progress = current.progress + 1; if (progress < focus.months) return { country, political, focus: { ...current, progress } }; const effects = focus.effects; return { country: { ...country, industry: Math.max(0, country.industry + (effects.industry ?? 0)), military: Math.max(0, country.military + (effects.military ?? 0)), gdpGrowth: country.gdpGrowth + (effects.gdpGrowth ?? 0) }, political: { ...political, publicApproval: Math.max(0, Math.min(100, political.publicApproval + (effects.approval ?? 0))), politicalStability: Math.max(0, Math.min(100, political.politicalStability + (effects.stability ?? 0))) }, focus: { activeId: null, progress: 0, completed: [...current.completed, focus.id] }, completed: focus }
}
