import { useGameStore } from '../store/gameStore'
import type { PolicyId } from '../types/game'
import { normalizePolitical } from '../game/politics/politicsEngine'
import { nationalFocuses } from '../game/politics/focusEngine'
const policies: [string, PolicyId, string][] = [['경제', 'market', '시장경제 강화'], ['경제', 'industry', '산업 육성'], ['경제', 'austerity', '긴축 재정'], ['복지', 'welfareUp', '복지 확대'], ['복지', 'welfareDown', '복지 축소'], ['군사', 'defense', '국방 강화'], ['군사', 'disarmament', '군비 축소'], ['사회', 'freedom', '자유 확대'], ['사회', 'control', '사회 통제 강화']]
export function PoliticsPanel() {
  const state = useGameStore(); const player = state.countries.find((country) => country.id === state.playerCountryId) ?? state.countries[0]; const political = normalizePolitical(player); const focus = state.nationalFocus?.[player.id] ?? { activeId: null, progress: 0, completed: [] }; const power = political.politicalPower ?? 60
  return <section className="politics-panel"><div className="panel-heading"><div><span className="eyebrow">국가 운영</span><h2>국내 정치</h2></div><span className="map-status">● 정책과 여론</span></div><div className="politics-content"><div className="political-head"><span>정부 형태 <b>{political.governmentType}</b></span><span>국민 지지율 <b>{political.publicApproval.toFixed(0)}%</b></span><span>정치 안정도 <b>{political.politicalStability.toFixed(0)}</b></span><span>정치력 <b>{power.toFixed(0)}</b></span><span>전쟁 피로도 <b>{(political.warExhaustion ?? 0).toFixed(0)}%</b></span></div><div className="political-leader"><span>지도자 <b>{political.leader?.name ?? '국가원수'}</b></span><span>집권 세력 <b>{political.factions?.find((faction) => faction.id === political.rulingFactionId)?.name ?? '정부'}</b></span><span>인기 <b>{political.leader?.popularity ?? 60}%</b></span></div><div className="political-factions"><div className="section-label">정치 세력</div>{(political.factions ?? []).map((faction) => <span key={faction.id}>{faction.name} <b>{faction.support.toFixed(0)}%</b></span>)}</div><div className="political-traits"><span>자유주의 {political.liberalism.toFixed(0)}</span><span>권위주의 {political.authoritarianism.toFixed(0)}</span><span>민족주의 {political.nationalism.toFixed(0)}</span><span>군국주의 {political.militarism.toFixed(0)}</span></div><div className="section-label policy-label">국가 정책</div><div className="policy-grid">{policies.map(([category, id, label]) => <button key={id} className={political.currentPolicies[category] === id ? 'policy-button active' : 'policy-button'} disabled={political.policyCooldown > 0 || power < 10} onClick={() => state.changePolicy(player.id, category, id)}>{political.currentPolicies[category] === id ? '● ' : '○ '}{label}</button>)}</div><small className="cooldown-label">{political.policyCooldown > 0 ? `정책 변경 가능까지 ${political.policyCooldown}개월` : '정책 변경 가능 · 정치력 10 필요'}</small><div className="section-label policy-label">국가 중점</div><div className="focus-grid">{nationalFocuses.map((item) => <button key={item.id} className={`policy-button ${focus.completed.includes(item.id) ? 'active' : ''}`} disabled={Boolean(focus.activeId) || focus.completed.includes(item.id)} onClick={() => state.startFocus(item.id)}>{focus.completed.includes(item.id) ? '✓ ' : focus.activeId === item.id ? `진행 중 ${focus.progress}/${item.months} · ` : ''}{item.name}</button>)}</div>{(state.domesticEvents ?? []).map((event) => <div className="domestic-event" key={event.id}><div className="section-label">국내 사건 · {event.title}</div><p>{event.description}</p><div className="event-actions">{event.choices.map((choice) => <button key={choice.id} className="diplomacy-action" onClick={() => state.resolveEvent(event.id, choice.id)}>{choice.label}</button>)}</div></div>)}</div></section>
}
