import type { Country, Fleet, RegionState, SeaRegion, ShipStock } from '../../types/game'

export const emptyShips = (): ShipStock => ({ carriers: 0, battleships: 0, cruisers: 0, destroyers: 0, submarines: 0, transports: 0 })
export function createSeaRegions(): SeaRegion[] { return [{ id: 'east-sea', name: '동해', coastalRegionIds: ['han-capital', 'japan-capital'], navalControl: {} }, { id: 'west-sea', name: '서해', coastalRegionIds: ['han-capital', 'china-capital'], navalControl: {} }, { id: 'south-sea', name: '남해', coastalRegionIds: ['han-capital', 'japan-capital'], navalControl: {} }, { id: 'strait', name: '대한해협', coastalRegionIds: ['han-capital', 'japan-capital'], navalControl: {} }] }
export function createInitialFleets(countries: Country[], territories: Record<string, RegionState[]>): Fleet[] { return countries.map((country) => ({ id: `fleet-${country.id}-1`, countryId: country.id, name: `${country.name} 제1함대`, ships: { carriers: 1, battleships: 2, cruisers: 4, destroyers: 12, submarines: 6, transports: 30 }, homePortRegionId: territories[country.id]?.[0]?.id ?? '', operationSeaIds: ['east-sea', 'west-sea'], mission: '해상권 확보', readiness: 78, training: 50, experience: 8, fuel: 82 })) }
export function fleetPower(fleet: Fleet) { const ships = fleet.ships; return (ships.carriers * 22 + ships.battleships * 18 + ships.cruisers * 10 + ships.destroyers * 5 + ships.submarines * 8) * (0.55 + fleet.training / 200) * fleet.readiness / 100 * fleet.fuel / 100 }
export function updateNavies(fleets: Fleet[], seas: SeaRegion[], wars: { attacker: string; defender: string; active: boolean }[], countries: Country[]) { const activeCountries = new Set(wars.filter((war) => war.active).flatMap((war) => [war.attacker, war.defender])); const next = fleets.map((fleet) => ({ ...fleet, mission: activeCountries.has(fleet.countryId) && fleet.mission === '대기' ? '해상권 확보' as const : fleet.mission, readiness: Math.min(100, fleet.readiness + (fleet.mission === '대기' ? 3 : -2)), fuel: Math.max(10, fleet.fuel - (fleet.mission === '대기' ? 1 : 3)) })); const control: Record<string, Record<string, number>> = {}; const blockades: Record<string, number> = {}; for (const sea of seas) { const byCountry = new Map<string, number>(); next.filter((fleet) => fleet.operationSeaIds.includes(sea.id)).forEach((fleet) => byCountry.set(fleet.countryId, (byCountry.get(fleet.countryId) ?? 0) + fleetPower(fleet))); const total = [...byCountry.values()].reduce((a, b) => a + b, 0) || 1; control[sea.id] = Object.fromEntries([...byCountry.entries()].map(([id, power]) => [id, Math.round(power / total * 100)])); }
  wars.filter((war) => war.active).forEach((war) => { const attacker = next.filter((fleet) => fleet.countryId === war.attacker).reduce((sum, fleet) => sum + fleetPower(fleet), 0); const defender = next.filter((fleet) => fleet.countryId === war.defender).reduce((sum, fleet) => sum + fleetPower(fleet), 0); if (attacker > defender * 1.15) blockades[war.defender] = Math.min(80, Math.round(attacker / Math.max(1, defender) * 25)); else if (defender > attacker * 1.15) blockades[war.attacker] = Math.min(80, Math.round(defender / Math.max(1, attacker) * 25)); });
  const updatedCountries = countries.map((country) => { const blockade = blockades[country.id] ?? 0; return blockade ? { ...country, gdp: Math.max(1, country.gdp * (1 - blockade / 1000)), treasury: Math.max(0, country.treasury - blockade / 10), gdpGrowth: country.gdpGrowth - blockade / 100 } : country }); return { fleets: next, navalControl: control, blockades, countries: updatedCountries }
}
