import { Header } from './components/Header'
import { WorldMap } from './components/WorldMap'
import { CountryPanel } from './components/CountryPanel'
import { GameLog } from './components/GameLog'
import { PoliticsPanel } from './components/PoliticsPanel'
import { ResearchPanel } from './components/ResearchPanel'
import { RegionPanel } from './components/RegionPanel'
import { ResourcePanel } from './components/ResourcePanel'
import { MilitaryPanel } from './components/MilitaryPanel'
import { AirNavyPanel } from './components/AirNavyPanel'
import { WorldHistoryPanel } from './components/WorldHistoryPanel'
import { SocietyPanel } from './components/SocietyPanel'
import { PoliticalInstitutionPanel } from './components/PoliticalInstitutionPanel'
import { EconomyPanel } from './components/EconomyPanel'
import { EconomicDeepPanel } from './components/EconomicDeepPanel'
import { DiplomacyPanel } from './components/DiplomacyPanel'
import { DomesticPoliticsPanel } from './components/DomesticPoliticsPanel'
import { IntelligencePanel } from './components/IntelligencePanel'
import { TechnologyPanel } from './components/TechnologyPanel'
import { InnovationPanel } from './components/InnovationPanel'
import { IntegrationPanel } from './components/IntegrationPanel'
import { AIDebugPanel } from './components/AIDebugPanel'
import { GameNavigation } from './components/GameNavigation'
import { NewsPanel } from './components/NewsPanel'
import { SavePanel } from './components/SavePanel'
import { NationalProfilePanel } from './components/NationalProfilePanel'
import { DynamicEventPanel } from './components/DynamicEventPanel'
import { DomesticPolitics2Panel } from './components/DomesticPolitics2Panel'
import { MainMenu } from './components/MainMenu'
import { TutorialBanner } from './components/TutorialBanner'
import './index.css'

export default function App() { return <div className="app-shell"><MainMenu /><Header /><TutorialBanner /><GameNavigation /><main><WorldMap /><CountryPanel /></main><NewsPanel /><DynamicEventPanel /><PoliticsPanel /><PoliticalInstitutionPanel /><SocietyPanel /><DomesticPoliticsPanel /><DomesticPolitics2Panel /><NationalProfilePanel /><IntegrationPanel /><AIDebugPanel /><EconomyPanel /><EconomicDeepPanel /><DiplomacyPanel /><IntelligencePanel /><TechnologyPanel /><InnovationPanel /><ResearchPanel /><ResourcePanel /><RegionPanel /><MilitaryPanel /><AirNavyPanel /><WorldHistoryPanel /><SavePanel /><GameLog /><footer>WORLD ORDER v1.0.0 <span>로컬 저장 활성화</span></footer></div> }
